site_name: Notas Musicais
repo_url: https://github.com/mfhorita/notas-musicais
repo_name: mfhorita/notas-musicais
edit_uri: tree/master/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  
markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css
